=== IdangMawardi/tugaswebservicexml/jasa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="jasa">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="perusahaan"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="perusahaan">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="biodata"/>
                <xs:element ref="detail"/>
            </xs:sequence>
            <xs:attribute name="jasa" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="biodata">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nama"/>
                <xs:element ref="alamat"/>
                <xs:element ref="telepon"/>
                <xs:element ref="email"/>
                <xs:element ref="kota"/>
                <xs:element ref="provinsi"/>
                <xs:element ref="negara"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nama" type="xs:string"/>
    <xs:element name="alamat" type="xs:string"/>
    <xs:element name="telepon" type="xs:integer"/>
    <xs:element name="email">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">
    			<xs:pattern
    				value="([0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*@([0-9a-zA-Z][-\w]*[0-9a-zA-Z]\.)+[a-zA-Z]{2,9})">
    			</xs:pattern>
    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="kota" type="xs:NCName"/>
    <xs:element name="provinsi" type="xs:string"/>
    <xs:element name="negara" type="xs:NCName"/>
    <xs:element name="detail">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="paket"/>
                <xs:element ref="harga"/>
                <xs:element ref="isi"/>
                <xs:element ref="berat"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="paket" type="xs:NCName"/>
    <xs:element name="harga" type="xs:integer"/>
    <xs:element name="isi" type="xs:string"/>
    <xs:element name="berat" type="xs:NMTOKEN"/>
</xs:schema>

=== IdangMawardi/tugaswebservicexml/jasa.xml
<?xml version="1.0" encoding="UTF-8"?>
<jasa xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jasa.xsd">
	<perusahaan jasa = "Global Cargo">
<biodata>
		<nama> Idang Mawardi</nama>
		<alamat>jln dago barat</alamat>
		<telepon>0222533965</telepon>
		<email>idangmawardi@gmail.com</email>
		<kota>Bandung</kota>
		<provinsi>Jawa Barat</provinsi>
		<negara>Indonesia</negara>	
</biodata>
<detail>
		<paket>Reguler</paket>
		<harga>30000</harga>
		<isi>TV</isi>
		<berat>8kg</berat>
</detail>
	</perusahaan>
	
	<perusahaan jasa = "JEN">
<biodata>
		<nama> Dodi</nama>
		<alamat>jln Sumbawa</alamat>
		<telepon>0222539999</telepon>
		<email>Dodi@gmail.com</email>
		<kota>Padang</kota>
		<provinsi>Sumatera Barat</provinsi>
		<negara>Indonesia</negara>	
</biodata>
<detail>
		<paket>Cepat</paket>
		<harga>50000</harga>
		<isi>Komputer</isi>
		<berat>9kg</berat>
</detail>
	</perusahaan>
	
	<perusahaan jasa = "LDH">
<biodata>
		<nama> Ayu</nama>
		<alamat>jln Jend. Sudirman</alamat>
		<telepon>08123000948</telepon>
		<email>AyuLestari@gmail.com</email>
		<kota>Denpasar</kota>
		<provinsi>Bali</provinsi>
		<negara>Indonesia</negara>	
</biodata>
<detail>
		<paket>Reguler</paket>
		<harga>500000</harga>
		<isi>Motor</isi>
		<berat>80kg</berat>
</detail>
	</perusahaan>
	
	<perusahaan jasa = "Fast Stuff">
<biodata>
		<nama> Joy</nama>
		<alamat>jln Jawa </alamat>
		<telepon>0222533965</telepon>
		<email>Joyjordinson@gmail.com</email>
		<kota>Pontianak</kota>
		<provinsi>Kalimantan</provinsi>
		<negara>Indonesia</negara>	
</biodata>
<detail>
		<paket>Reguler</paket>
		<harga>25000</harga>
		<isi>Baju</isi>
		<berat>12kg</berat>
</detail>
	</perusahaan>
	
	<perusahaan jasa = "Fast Come">
<biodata>
		<nama> Rudy</nama>
		<alamat>jln Kalimaya</alamat>
		<telepon>0212533465</telepon>
		<email>Rudysimorangkir@gmail.com</email>
		<kota>Jakarta</kota>
		<provinsi>Jakarta</provinsi>
		<negara>Indonesia</negara>	
</biodata>
<detail>
		<paket>Cepat</paket>
		<harga>1500000</harga>
		<isi>Sound System</isi>
		<berat>55kg</berat>
</detail>
	</perusahaan>
</jasa>
